global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gatewayservice:8081"]
  - job_name: "webapp"
    static_configs:
      - targets: [ "webapp:3000" ]